export const colors = [
  { name: "BLACK", value: "#000000" },
  { name: "WHITE", value: "#ffffff" },
  { name: "RED", value: "#9a0000" },
  { name: "CYAN", value: "#a590e8" },
  { name: "PURPLE", value: "#b472d0" },
  { name: "GREEN", value: "#9fe339" },
  { name: "BLUE", value: "#352879" },
  { name: "YELLOW", value: "#fff780" },
  { name: "ORANGE", value: "#d49a44" },
  { name: "BROWN", value: "#433900" },
  { name: "PINKY / LIGHT RED", value: "#f6ab96" },
  { name: "DARK GREY", value: "#656565" },
  { name: "MID GREY", value: "#b1b1b1" },
  { name: "LIGHT GREEN", value: "#e4ffb5" },
  { name: "SKY / LIGHT BLUE", value: "#a9f3fe" },
  { name: "LIGHT GREY", value: "#d8e4e4" },
];
