import type { Metadata } from "next";

import Sidebar from "./components/Sidebar";

import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row">
          {/* Sidebar */}
          <Sidebar />
          {/* Main Content */}
          <div className="flex-1 p-2 m-2 bg-stone-800 border-green-600 md:ml-0 mt-16 md:mt-0">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
