import type { Metadata } from "next";
import { ComponentProvider } from './context/ComponentContext';
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";
import localFont from "next/font/local";
import "./globals.css";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const cascadiaCode = localFont({
  src: "./fonts/CascadiaCode.woff2",
  variable: "--font-cascadia-code",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cascadiaCode.variable} antialiased`}
      >
        <ComponentProvider>
          <div className="flex flex-col h-screen">
            <Topbar />
            <div className="flex flex-row h-full">
              <Sidebar />
              <div className="flex-1 p-2 m-2 bg-stone-800 border-green-600 md:ml-0 mt-0">

                {children}
              </div>
            </div>
          </div>
        </ComponentProvider>
      </body>
    </html>
  );
}
