import type { Metadata } from "next";
import { ComponentProvider } from './context/ComponentContext';
import { ChatProvider } from './context/ChatContext';
import ResizableSidebar from "./components/ResizableSidebar";
import Topbar from "./components/Topbar";
import localFont from "next/font/local";
import "./globals.css";



const geistSans = localFont({
  src: "./res/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./res/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const cascadiaCode = localFont({
  src: "./res/fonts/CascadiaCode.woff2",
  variable: "--font-cascadia-code",
  weight: "100 900",
});

const cascadiaMonoNF = localFont({
  src: "./res/fonts/CascadiaMonoNF.woff2",
  variable: "--font-cascadia-mono-nf",
  weight: "100 400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} ${cascadiaCode.className} ${cascadiaMonoNF.className} antialiased`}
      >
        <ComponentProvider>
          <ChatProvider>
            <div className="flex flex-col h-screen">
              <Topbar />
              <div className="flex flex-row h-full">
                <ResizableSidebar />
                <div className="flex-1 p-2 m-2 bg-stone-800 border-green-600 md:ml-0 mt-0">

                  {children}
                </div>
              </div>
            </div>
          </ChatProvider>
        </ComponentProvider>
      </body>
    </html>
  );
}
